---
name: cmpsc-101-fall-2018-lab2
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        labtwo/Sentences.java:
            --multi 9 --language Java
src/main:
    java:
        labtwo/SentencesReverser.java:
            --multi 2 --language Java
            --fragment "println(" --count 5 --exact
src/test:
    java:
        labtwo/TestSentences.java:
            --fragment "@Test" --count 3 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 5 --exact
    --words 100
# --> check the number of commits beyond a threshold
--commits 21
# --> check that the program executes and produces 26 lines of output
# --> check that the program produces output with certain fragments
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 26 --exact
--command "gradle -q --console plain run" --fragment "First" --count 2 --exact
--command "gradle -q --console plain run" --fragment "Tenth" --count 2 --exact
--command "gradle -q --console plain run" --fragment "Done" --count 3 --exact
